# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[font]
normal.family = "MonoLisa Nerd Font"
bold.family = "MonoLisa Nerd Font"
italic.family = "MonoLisa Nerd Font"
bold_italic.family = "MonoLisa Nerd Font"

[window]
blur = true
decorations = "Buttonless"
opacity = 0.9
padding.x = 8 
padding.y = 8
startup_mode = "Maximized"

