# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[colors]
primary.background = "#030712"

[font]
normal.family = "MonoLisa Nerd Font"
bold.family = "MonoLisa Nerd Font"
italic.family = "MonoLisa Nerd Font"
bold_italic.family = "MonoLisa Nerd Font"
size = 12

[window]
blur = true
decorations = "Buttonless"
opacity = 0.88
padding = { x = 0, y = 0 }
startup_mode = "Maximized"

