# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[colors]
primary.background = "#1E1D2D"

[env]
TERM = "xterm-256color"

[font]
normal.family = "MonoLisa Nerd Font"
bold.family = "MonoLisa Nerd Font"
italic.family = "MonoLisa Nerd Font"
bold_italic.family = "MonoLisa Nerd Font"
size = 12

[window]
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
padding = { x = 0, y = 2 }
startup_mode = "Maximized"

